apiVersion: v1
kind: Service
metadata:
  name: nginx-service-node
  namespace: netology
spec:
  type: NodePort
  selector:
    app: nginx-apps-node
  ports: 
    - name: http-svc-web
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
    - name: http-svc-mtt
      protocol: TCP
      port: 8080
      targetPort: 1180
      nodePort: 30002