apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: netology
spec: 
  selector:
    app: nginx-apps
  ports: 
    - name: http-svc-web
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: http-svc-mtt
      protocol: TCP
      port: 9002
      targetPort: 1180