{
 "title": "netology_solution_2",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Disk Free Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job=\"node\", instance=\"node-exporter:9100\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 * (rate(node_cpu_seconds_total{mode=\"system\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"node\", instance=\"node-exporter:9100\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15;",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "node_load1{job=\"node\", instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{job=\"node\", instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load15{job=\"node\", instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}