---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

    
- name: Install Vector
  hosts: vector
  roles:
    - vector

- name: Install lighthouse
  # hosts: click-srv
  hosts: lighthouse
  roles:
    - lighthouse