apiVersion: v1
kind: Service
metadata:
  name: network-service
  namespace: app
spec:
  selector:
    app: cache
  ports:
    - protocol: TCP
      name: multitool
      port: 9002
      targetPort: 1180