---
- name: PLAY - Install nginx
  hosts: lighthouse
  handlers:
    - name: start-nginx
      become: true
      ansible.builtin.command: nginx
      register: nginx_start_output
    - name: reload-nginx
      become: true
      ansible.builtin.command: nginx -s reload
      register: nginx_reload_output
  tasks:
    - name: NGINX | Install epel-release
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: NGINX | Install NGINX
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: NGINX | Create general config
      become: true
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
      notify: reload-nginx

- name: PLAY - Install LightHouse
  hosts: lighthouse
  vars_files:
    - ./group_vars/lighthouse/vars.yml
  handlers:
    - name: reload-nginx
      become: true
      ansible.builtin.command: nginx -s reload
  pre_tasks:
    - name: LIGHTHOUSE | Installing Git
      become: true
      ansible.builtin.yum:
        name: git
        state: present
  tasks:
    - name: LIGHTHOUSE | get Lighthouse source
      become: true
      git:
        repo: "{{ lighthouse_vcs }}"
        version: master
        dest: "{{ lighthouse_location_dir }}"
    - name: LIGHTHOUSE | Creating vector config
      become: true
      template:
        src: templates/lighthouse.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: 0644
      notify: reload-nginx

- name: PLAY - Install Clickhouse
  hosts: clickhouse
  tags: clickhouse
  vars_files:
    - ./group_vars/clickhouse/vars.yml
  handlers:
    - name: start-clickhouse-service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: CLICKHOUSE | Get distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: CLICKHOUSE | Get rescue distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
            mode: 0644

    - name: CLICKHOUSE | Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: start-clickhouse-service

    - name: CLICKHOUSE | Flush handlers
      ansible.builtin.meta: flush_handlers
      notify: start-clickhouse-service

    # - name: Start-clickhouse-service
    #   become: true
    #   ansible.builtin.service:
    #     name: clickhouse-server
    #     state: restarted

    - name: CLICKHOUSE | Create database
      # become: true
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

- name: Install Vector
  tags: vector
  hosts: vector
  vars_files:
    - ./group_vars/vector/vars.yml
  handlers:
    - name: restart-vector-service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: VECTOR | download Vector distr
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
        dest: "./vector-{{ vector_version }}.rpm"
        mode: 0644
    - name: Install Vector 
      become: true
      ansible.builtin.yum:
        name:
          - vector-{{ vector_version }}.rpm
    - name: VECTOR | creating vector config
      become: true
      ansible.builtin.file:
        path: "{{ vector_conf_dir }}"
        state: directory
        mode: 0644
    - name: VECTOR | apply vector template
      become: true
      ansible.builtin.template:
        src: "templates/vector.j2"
        dest: "{{ vector_conf_dir }}/vector.yml"
        mode: "0644"
      notify: restart-vector-service
    - name: Flush handlers
      ansible.legacy.meta: flush_handlers
      notify: restart-vector-service
    - name: VECTOR | Create systemd
      become: true
      ansible.builtin.template:
        src: vector.service.j2
        dest: /etc/systemd/system/vector.service
        mode: 0644
    - name: VECTOR | start vector service
      become: true
      ansible.builtin.systemd:
        name: vector
        state: started
        daemon_reload: true