apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-frontend
  name: nginx-app-deployment
spec:
  selector:
    matchLabels:
      app: nginx-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-frontend
    spec:
      containers:
        - name: nginx-app
          image: nginx:latest