apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-frontend-prod
  name: nginx-app-deployment-production
  namespace: production
spec:
  selector:
    matchLabels:
      app: nginx-frontend-prod
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-frontend-prod
    spec:
      containers:
        - name: nginx-prod-app
          image: nginx:latest